name: Auto Approve Pull Requests by SRDEVOPS

on:
  pull_request

jobs:

  call-auto-approve-reusable:
    uses: darnone/reusable-github-workflows/.github/workflows/auto-approve-reusable.yaml@main
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
      github_token: ${{ secrets.GITHUB_TOKEN }}
      sr_token: ${{ secrets.SR_TOKEN }}
      auto_approve_token: ${{ secrets.AUTO_APPROVE_TOKEN }}
