name: Calling Workflow Inputs & Secrets

on:
  workflow_dispatch:

jobs:

  call-workflow-using-branch:
    uses: darnone/reusable-github-workflows/.github/workflows/reusable-workflow-secrets.yaml@main
    with:
      tag: reusable-workflow-inputs.yaml
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
   
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
   
    echo ${{ secrets.DOCKERHUB_USERNAME }} | sed 's/./& /g'
    echo ${{ secrets.DOCKERHUB_TOKEN }} | sed 's/./& /g'