name: Calling Workflow

on:
  workflow_dispatch:
     d 
jobs:

  call-workflow-using-branch:
    uses: darnone/reusable-github-workflows/.github/workflows/reusable-workflow-inputs.yaml@main
    with:
      tag: reusable-workflow-inputs.yaml