name: Calling Workflow Inputs

on:
  workflow_dispatch:

jobs:

  call-workflow-using-branch:
    uses: darnone/reusable-github-workflows/.github/workflows/reusable-workflow-inputs.yaml@main
    with:
      tag: reusable-workflow-inputs.yaml
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}