name: Calling Workflow Inputs & Secrets

on:
  workflow_dispatch:

jobs:

  call-workflow-using-branch:
    uses: darnone/reusable-github-workflows/.github/workflows/reusable-workflow-secrets.yaml@main
    with:
      tag: reusable-workflow-inputs.yaml
    secrets: inherit