name: pull-request-lint

on:
  pull_request_target:
    types:
      - labeled
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - edited

jobs:

  call-pull-request-lint-reusable:
    uses: darnone/reusable-github-workflows/.github/workflows/pull-request-lint-reusable.yaml@main
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
      github_token: ${{ secrets.GITHUB_TOKEN }}
